#!/usr/local/bin/php
<?php


require_once('config.inc');
require_once('util.inc');
require_once('interfaces.inc');


$model = new \OPNsense\Tailscale\Settings();
$enabled = $model->enabled->__toString();


if (!$enabled) {
    exit(0);
}

$carpif = $model->carpIf->__toString();

if ($carpif == '') {
    exit(0);
}

$target_vhid = $model->vhid;
$subsystem = !empty($argv[1]) ? $argv[1] : '';
$type = !empty($argv[2]) ? $argv[2] : '';

if ($type != 'MASTER' && $type != 'BACKUP') {
    exit(1);
}

if (!strstr($subsystem, '@')) {
    exit(1);
}

list ($vhid, $iface) = explode('@', $subsystem);
$friendly = convert_real_interface_to_friendly_interface_name($iface);


if ($carpif != $friendly || $vhid != $target_vhid) {
    exit(0);
}

$backend = new \OPNsense\Core\Backend();
switch ($type) {
    case 'MASTER':
        touch('/var/run/tailscale/CARP_MASTER');
        $backend->configdRun('tailscale start');
        break;
    case 'BACKUP':
        if (file_exists('/var/run/tailscale/CARP_MASTER')) {
            unlink('/var/run/tailscale/CARP_MASTER');
        }
        $backend->configdRun('tailscale stop');
        break;
}

