PLUGIN_NAME=		netbird
PLUGIN_VERSION=		0.6
PLUGIN_DEPENDS=	    netbird
PLUGIN_REVISION=	1
PLUGIN_COMMENT=		Netbird plugin
PLUGIN_MAINTAINER=	support@netbird.io
PLUGIN_WWW=		    https:/netbird.io
PLUGIN_DEVEL=       no
PLUGIN_SUFFIX=
.include "../../Mk/plugins.mk"
