PLUGIN_NAME=		tailscale
PLUGIN_VERSION=		0.1
PLUGIN_DEPENDS=	    tailscale
PLUGIN_REVISION=	1
PLUGIN_COMMENT=		Tailscale plugin
PLUGIN_MAINTAINER=	moser@pjm.co.at
PLUGIN_WWW=		    https:/tailscale.com
PLUGIN_DEVEL=       no
PLUGIN_SUFFIX=
.include "../../Mk/plugins.mk"
